### ISSUE TITLE
Code (Git Workflow) Review

### ISSUE THREAD

**Issue by elsabenzinger** [ironicator/MK_Krypta#25]
I have looked through your git and have the following feedback.

Your readme looks great! It's very thorough and you get a clear understanding of what you want to do and how far you've come.

The commit-messages are good. It's clear what you are working on, but you could try to incorporate the issue number as well to make it even clearer! 

When it comes to issues you don't seem to have been closed very many (unless the 13 missing ones have been closed and deleted) and you have not used milestones. A tip is to use milestones for the big, changes you want to make and then connect issues to it, where the issues are smaller parts of what needs to be completed for the milestone. You can then see how much progress you have made on a specific milestone and you can commit smaller things to git to make the merge-process easier.

The labels on the issues are clear!

Your naming of branches are good and you seem to be using branching in the way they were meant (code, commit, merge).

Overall very good work. Good luck on your investing algorithms and neural networks! :)

**Comment by Riehantunut** [comment]
Thx for the review!
